-
  messInID: 1907972254120721511
  fcCode:
  groupNo: 200010838
  msgKeys:
      amount: 1
      productName: 1234
      file_info:
      targetphone: RC5vmch6P7EzPNMeeKVcvQ==
      accountName: 你好
      clientName: 123
      name: 1
      key: 1
  sceneId: jingxuan12345
  sendTime:
  banTimeFlag: Y
  messagereply: 0
  intervalTime:
  ignoreSettingFlag: Y
  businessCategory:
  copySend:

#-
#  messInID: 1907972254120721512
#  fcCode:
#  groupNo: 200010838
#  msgKeys:
#      amount: 1
#      productName: 1234
#      file_info:
#      targetphone: RC5vmch6P7EzPNMeeKVcvQ==
#      accountName: 你好
#      clientName: 123
#      name: 1
#      key: 1
#  sceneId: jing987
#  sendTime:
#  banTimeFlag: Y
#  messagereply: 0
#  intervalTime:
#  ignoreSettingFlag: Y
#  businessCategory:
#  copySend:
